apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    anywhere.eks.amazonaws.com/management-components-version: v0.0.0-dev+build.8207
  name: main-i-0cc36-2c27bc6
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
  datacenterRef:
    kind: DockerDatacenterConfig
    name: main-i-0cc36-2c27bc6
  eksaVersion: v0.0.0-dev+build.8207
  externalEtcdConfiguration:
    count: 1
  gitOpsRef:
    kind: FluxConfig
    name: eksa-test
  kubernetesVersion: "1.28"
  machineHealthCheck:
    nodeStartupTimeout: 10m0s
    unhealthyMachineTimeout: 5m0s
  managementCluster:
    name: main-i-0cc36-2c27bc6
  workerNodeGroupConfigurations:
  - count: 1
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: DockerDatacenterConfig
metadata:
  name: main-i-0cc36-2c27bc6
  namespace: default
spec: {}

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: eksa-test
  namespace: default
spec:
  branch: quick-e2e-test-6c0f06b2-1b0e-456d-a0e9-672c5e7a7dcd-3
  clusterConfigPath: quick-e2e-test-6c0f06b2-1b0e-456d-a0e9-672c5e7a7dcd-3
  git:
    repositoryUrl: ssh://git@github.com/that-jetpack-guy/quick-e2e-test-6c0f06b2-1b0e-456d-a0e9-672c5e7a7dcd-3.git
  systemNamespace: default

---
